site_name: Truffle Suite
site_url: https://trufflesuite.com
docs_dir: src
site_dir: site
theme:
  name: 'material'
  custom_dir: 'custom_theme/'
  logo: assets/logo.png
  favicon: assets/favicon-32x32.png  
  palette:
    scheme: default
  font:
    text: "Open Sans"
    code: "Open Sans"
  features:
    - navigation.tabs
  language: en
copyright: Copyright &copy; 2016 - 2022 ConsenSys Software Inc.
extra:
  analytics:
    provider: google
    property: UA-83874933-3
  generator: false
  social:
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/trufflesuite
    name: Truffle Twitter
  - icon: fontawesome/brands/github
    link: https://github.com/trufflesuite
    name: Truffle Github
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/company/trufflesuite
    name: Truffle LinkedIn
  rebuild: false    
extra_css:
  - assets/stylesheets/bootstrap.min.css
  - assets/stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - markdown.extensions.md_in_html
  - attr_list
  - toc:
      permalink: true
use_directory_urls: true
plugins:
  - search
  - exclude-search:
      exclude:
        - blog/the-best-things-to-do-in-seattle-during-trufflecon
        - events/*
        - staff/*
        - trufflecon2020/*
      exclude-unreferenced: true
  - awesome-pages
  - macros:
      module_name: main
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      js_files:
          - assets/js/dashboard.js
          - assets/js/os-detector.js
      css_files:
          - assets/stylesheets/dashboard.css
          - assets/stylesheets/extra.css
