site_name: Truffle Suite
site_url: https://trufflesuite.com
docs_dir: src
site_dir: site
theme:
  name: 'material'
  custom_dir: 'custom_theme/'
  logo: assets/logo.png
  favicon: assets/favicon-32x32.png  
  palette:
    scheme: default
  font:
    text: "Open Sans"
    code: "Open Sans"
  features:
    - navigation.tabs
  language: en
copyright: Copyright &copy; 2016 - 2022 ConsenSys Software Inc.
extra:
  analytics:
    provider: google
    property: UA-83874933-3
  generator: false
  social:
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/trufflesuite
    name: Truffle Twitter
  - icon: fontawesome/brands/github
    link: https://github.com/trufflesuite
    name: Truffle Github
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/company/trufflesuite
    name: Truffle LinkedIn
  rebuild: false    
extra_css:
  - assets/stylesheets/bootstrap.min.css
  - assets/stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - markdown.extensions.md_in_html
  - attr_list
  - toc:
      permalink: true
use_directory_urls: true
plugins:
  - search
  - exclude-search:
      exclude:
        - blog/the-best-things-to-do-in-seattle-during-trufflecon
        - events/*
        - staff/*
        - trufflecon2020/*
      exclude-unreferenced: true
  - awesome-pages
  - macros:
      module_name: main
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      js_files:
          - assets/js/dashboard.js
          - assets/js/os-detector.js
      css_files:
          - assets/stylesheets/dashboard.css
          - assets/stylesheets/extra.css
  - redirects:
      redirect_maps:
        'tutorial/index.md': 'guides/pet-shop/index.md'
        'tutorial/pet-shop/index.md': 'guides/pet-shop/index.md'
        'tutorials/index.md': 'guides/pet-shop/index.md'
        'tutorials/pet-shop/index.md': 'guides/pet-shop/index.md'
        'docs/ganache/overview/index.md': 'docs/ganache/index.md'
#       Truffle docs restructure
        'docs/truffle/getting-started/compiling-contracts.md': 'docs/truffle/how-to/compile-contracts.md'
        'docs/truffle/getting-started/creating-a-project.md': 'docs/truffle/how-to/create-a-project.md'
        'docs/truffle/getting-started/installation.md': 'docs/truffle/how-to/install.md'
        'docs/truffle/getting-started/interacting-with-your-contracts.md': 'docs/truffle/how-to/contracts/interact-with-your-contracts.md'
        'docs/truffle/getting-started/package-management-via-ethpm.md': 'docs/truffle/how-to/package-management-via-npm.md'
        'docs/truffle/getting-started/package-management-via-npm.md': 'docs/truffle/how-to/package-management-via-npm.md'
        'docs/truffle/getting-started/preserving-files-and-content-to-storage-platforms.md': 'docs/truffle/how-to/preserve-files-and-content-to-storage-platforms.md'
        'docs/truffle/getting-started/running-migrations.md': 'docs/truffle/how-to/contracts/run-migrations.md'
        'docs/truffle/getting-started/truffle-with-metamask.md': 'docs/truffle/how-to/truffle-with-metamask.md'
        'docs/truffle/getting-started/using-the-build-pipeline.md': 'docs/truffle/how-to/use-the-build-pipeline.md'
        'docs/truffle/getting-started/using-the-truffle-dashboard.md': 'docs/truffle/how-to/use-the-truffle-dashboard.md'
        'docs/truffle/getting-started/using-the-truffle-debugger.md': 'docs/truffle/how-to/debug-test/use-the-truffle-debugger.md'
        'docs/truffle/getting-started/using-truffle-develop-and-the-console.md': 'docs/truffle/how-to/debug-test/use-truffle-develop-and-the-console.md'
        'docs/truffle/testing/testing-your-contracts.md': 'docs/truffle/how-to/debug-test/test-your-contracts.md'
        'docs/truffle/testing/writing-tests-in-javascript.md': 'docs/truffle/how-to/debug-test/write-tests-in-javascript.md'
        'docs/truffle/testing/writing-tests-in-solidity.md': 'docs/truffle/how-to/debug-test/write-tests-in-solidity.md'
        'docs/truffle/getting-started/writing-external-scripts.md': 'docs/truffle/how-to/write-external-scripts.md'
        'docs/truffle/distributed-ledger-support/working-with-hyperledger-evm.md': 'docs/truffle/how-to/distributed-ledger-support/hyperledger-evm.md'
        'docs/truffle/distributed-ledger-support/working-with-quorum.md': 'docs/truffle/how-to/distributed-ledger-support/quorum.md'
        'docs/truffle/advanced/creating-a-truffle-box.md': 'docs/truffle/how-to/create-a-truffle-box.md'
        'docs/truffle/advanced/build-processes.md': 'docs/truffle/concepts/build-processes.md'
        'docs/truffle/advanced/ethereum-name-service.md': 'docs/truffle/concepts/ethereum-name-service.md'
        'docs/truffle/advanced/event-system.md': 'docs/truffle/concepts/event-system.md'
        'docs/truffle/advanced/networks-and-app-deployment.md': 'docs/truffle/concepts/networks-and-app-deployment.md'
        'docs/truffle/reference/contact-the-developers.md': 'docs/truffle/contact-the-developers.md'
        'docs/truffle/reference/choosing-an-ethereum-client.md': 'docs/truffle/concepts/ethereum-client-types.md'
        'docs/truffle/reference/truffle-commands.md': 'docs/truffle/reference/command-line-options.md'
#       Filecoin docs restructure
        'docs/filecoin/truffle/quickstart.md': 'docs/truffle/concepts/filecoin.md'
        'docs/filecoin/ganache/getting-started/get-started-with-nodejs.md': 'docs/ganache/how-to/work-with-filecoin/get-started-with-nodejs.md'
        'docs/filecoin/ganache/getting-started/get-started-with-the-cli.md': 'docs/ganache/how-to/work-with-filecoin/get-started-with-the-cli.md'
        'docs/filecoin/ganache/getting-started/get-started-with-the-gui.md': 'docs/ganache/how-to/work-with-filecoin/get-started-with-the-gui.md'
        'docs/filecoin/ganache/overview.md': 'docs/ganache/how-to/work-with-filecoin/overview.md'
#       Ganache docs restructure
        'docs/ganache/corda/cordapps.md': 'docs/ganache/concepts/corda-workspace/cordapps.md'
        'docs/ganache/corda/nodes.md': 'docs/ganache/concepts/corda-workspace/nodes.md'
        'docs/ganache/corda/shell.md': 'docs/ganache/concepts/corda-workspace/shell.md'
        'docs/ganache/corda/transactions.md': 'docs/ganache/concepts/corda-workspace/transactions.md'
        'docs/ganache/corda/workspace-overview.md': 'docs/ganache/concepts/corda-workspace/overview.md'
        'docs/ganache/truffle-projects/contracts-page.md': 'docs/ganache/concepts/ethereum-workspace/contracts-page.md'
        'docs/ganache/truffle-projects/decoded-transactions.md': 'docs/ganache/concepts/ethereum-workspace/decoded-transactions.md'
        'docs/ganache/workspaces/ethereum-workspace-overview.md': 'docs/ganache/concepts/ethereum-workspace/overview.md'
        'docs/ganache/truffle-projects/events-page.md': 'docs/ganache/concepts/ethereum-workspace/events-page.md'
        'docs/ganache/truffle-projects/linking-a-truffle-project.md': 'docs/ganache/how-to/link-a-truffle-project.md'
        'docs/ganache/truffle-projects/unlinking-a-truffle-project.md': 'docs/ganache/how-to/unlink-a-truffle-project.md'
        'docs/ganache/corda/linking-a-corda-project.md': 'docs/ganache/how-to/work-with-corda/link-a-corda-project.md'
        'docs/ganache/corda/unlinking-a-corda-project.md': 'docs/ganache/how-to/work-with-corda/unlink-a-corda-project.md'
        'docs/ganache/workspaces/creating-workspaces.md': 'docs/ganache/how-to/workspaces/create-workspaces.md'
        'docs/ganache/workspaces/deleting-workspaces.md': 'docs/ganache/how-to/workspaces/delete-workspaces.md'
        'docs/ganache/workspaces/editing-workspaces.md': 'docs/ganache/how-to/workspaces/edit-workspaces.md'
        'docs/ganache/workspaces/loading-existing-workspaces.md': 'docs/ganache/how-to/workspaces/load-existing-workspaces.md'
        'docs/ganache/workspaces/switching-workspaces.md': 'docs/ganache/how-to/workspaces/switch-workspaces.md'
        'docs/ganache/workspaces/the-quickstart-workspace.md': 'docs/ganache/how-to/workspaces/the-quickstart-workspace.md'
        'docs/ganache/corda/working-with-corda.md': 'docs/ganache/concepts/corda-workspace/overview.md'
        'docs/vscode-ext/installation-guide.md': 'docs/vscode-ext/how-to/install-dependencies.md'
        'docs/vscode-ext/infura-blockchain-service-management.md': 'docs/vscode-ext/how-to/connect-to-infura.md'
        'docs/vscode-ext/contract-management.md': 'docs/vscode-ext/how-to/manage-smart-contracts.md'
        'docs/vscode-ext/debugging-smart-contracts.md': 'docs/vscode-ext/how-to/debug-smart-contracts.md'
        'docs/vscode-ext/faq.md': 'docs/vscode-ext/how-to/troubleshoot.md'
        'docs/vscode-ext/command-palette.md': 'docs/vscode-ext/reference/command-palette.md'
        'guides/ethereum-overview/index.md': 'guides/index.md'
        'dashboard': 'docs/truffle/how-to/use-the-truffle-dashboard.md'